//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckOut
    {
        public decimal CheckOut_ID { get; set; }
        public decimal User_ID { get; set; }
        public decimal Movie_ID { get; set; }
        public System.DateTime Due_Date { get; set; }
    
        public virtual Movy Movy { get; set; }
        public virtual User User { get; set; }
    }
}
